#:schema node_modules/wrangler/config-schema.json
name = "jwt"
main = "src/index.js"
compatibility_date = "2024-06-20"
compatibility_flags = ["nodejs_compat"]


[vars]
vars = {SECRET_KEY = "ASFSDFJDSJFJDSKFSDKLJF1314234234",EMAIL_FROM="info@orbitlabs.xyz", FRONTEND_URL= "http://127.0.0.1:8080/",API_URL = "https://htmxdatabase.orbitlabsworker.workers.dev", EMAIL_API_URL="https://email-mailchannel.orbitlabsworker.workers.dev",  PRODUCT_NAME="HTMX Fun", SENDER_EMAIL_NAME="htmxfun"}


[[d1_databases]]
binding = "DB"
database_name = "htmx"
database_id = "b9b6406b-0c3a-4e07-aa4d-3ac5e550dd53"



[env.local]
vars = {SECRET_KEY = "ASFSDFJDSJFJDSKFSDKLJF1314234234",EMAIL_FROM="info@orbitlabs.xyz", FRONTEND_URL= "http://127.0.0.1:8080/", API_URL = "http://localhost:8787/", EMAIL_API_URL="https://email-mailchannel.orbitlabsworker.workers.dev", PRODUCT_NAME="HTMX Fun", SENDER_EMAIL_NAME="htmxfun"}


[[env.local.d1_databases]]
binding = "DB"
database_name = "htmx"
database_id = "b9b6406b-0c3a-4e07-aa4d-3ac5e550dd53"

