#:schema node_modules/wrangler/config-schema.json
name = "jwt"
main = "src/index.js"
compatibility_date = "2024-06-20"
compatibility_flags = ["nodejs_compat"]



[env.production]
vars = {SECRET_KEY = "ASFSDFJDSJFJDSKFSDKLJF1314234234"}

[[env.production.d1_databases]]
binding = "DB"
database_name = "htmx"
database_id = "b9b6406b-0c3a-4e07-aa4d-3ac5e550dd53"

[env.local]
vars = {SECRET_KEY = "ASFSDFJDSJFJDSKFSDKLJF1314234234"}

[[env.local.d1_databases]]
binding = "DB"
database_name = "htmx"
database_id = "b9b6406b-0c3a-4e07-aa4d-3ac5e550dd53"